### ISSUE TITLE
Django 서버 생성 및 기초 작업 준비, DB 입력까지

### ISSUE THREAD

**Issue by junodak** [HARl803/recommend-service#1]
## Description
- Django 프로젝트를 생성하고, `estimate` 앱을 추가합니다. DB 모델을 설계하고 초기 데이터를 DB에 입력합니다.

## Todo
- [x] Django 프로젝트 생성 (`django-admin startproject`)
- [x] `estimate` 앱 생성 및 설정 파일에 앱 추가 (`INSTALLED_APPS`에 추가)
- [x] `PC` 모델 정의 (`estimate_models.py`에 정의)
- [x] 모델 마이그레이션 파일 생성 (`python manage.py makemigrations`)
- [x] 초기 마이그레이션 수행 (`python manage.py migrate`)
- [x] `pc.json` 파일을 사용하여 초기 데이터 DB에 입력 (`python manage.py loaddata pc.json`)
