### ISSUE TITLE
DB 데이터를 모델의 input으로 넣을 수 있게 가공 및 가공된 데이터 get 요청

### ISSUE THREAD

**Issue by junodak** [HARl803/recommend-service#2]
## Description
- DB에 저장된 데이터를 모델의 입력 형식에 맞게 가공하고, 가공된 데이터를 API로 제공할 수 있도록 합니다.

## Todo
- [x] DB에서 PC 데이터 로드 (`estimate_train_model.py`에서 `PC` 모델 사용)
- [x] 데이터 전처리 및 인코딩 수행 (`estimate_train_model.py`에서 `process_data` 함수 구현)
- [x] 가공된 데이터를 반환하는 `preview_data` API 엔드포인트 구현 (`estimate_views.py`에서 구현)
- [x] `preview_data` 엔드포인트를 `urls.py`에 추가 (`estimate_urls.py`에 추가)
- [x] 가공된 데이터가 정상적으로 반환되는지 테스트
